<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Softmax" data-toc-modified-id="Softmax-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Softmax</a></span></li><li><span><a href="#Tensors-are-just-rectangles!" data-toc-modified-id="Tensors-are-just-rectangles!-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Tensors are just rectangles!</a></span></li></ul></div>

# Softmax

In [ ]:
import torch

In [ ]:
# 3 imgs, output has 10 activations per img
im1 = torch.randn(10)
im2 = torch.randn(10)
im3 = torch.randn(10)
im1

tensor([ 0.1332,  0.6272,  0.9774, -1.1850,  0.3530,  0.2776,  0.9024,  1.0016,
         0.9419, -1.1489])

In [ ]:
ims = torch.stack((im1,im2,im3),0)
ims

tensor([[ 0.1332,  0.6272,  0.9774, -1.1850,  0.3530,  0.2776,  0.9024,  1.0016,
          0.9419, -1.1489],
        [-0.3813,  0.3184, -0.7167, -1.1152, -0.2556, -0.1563,  1.2510, -0.8549,
         -1.2150,  0.8789],
        [ 1.2981,  0.3528,  1.9857, -2.4427,  0.7066,  0.3762, -0.7110,  1.3030,
         -0.0151, -0.3545]])

In [ ]:
ims.shape

torch.Size([3, 10])

In [ ]:
def softmax(t):
    if len(t.shape) == 1: return torch.exp(t) / torch.exp(t).sum()
    else:                 return torch.exp(t) / torch.exp(t).sum(dim=1, keepdim=True)

In [ ]:
softmax(im1)

tensor([0.0680, 0.1115, 0.1583, 0.0182, 0.0848, 0.0786, 0.1468, 0.1622, 0.1527,
        0.0189])

In [ ]:
softmax(ims)

tensor([[0.0680, 0.1115, 0.1583, 0.0182, 0.0848, 0.0786, 0.1468, 0.1622, 0.1527,
         0.0189],
        [0.0614, 0.1235, 0.0439, 0.0295, 0.0696, 0.0769, 0.3140, 0.0382, 0.0267,
         0.2164],
        [0.1680, 0.0653, 0.3342, 0.0040, 0.0930, 0.0668, 0.0225, 0.1688, 0.0452,
         0.0322]])

# Tensors are just rectangles!

Good news! You have a brilliantly intuitive grasp of tensors, smartypants. I'm just going to draw it out of you with a few simple words and analogies. But remember: you already have the power. You already *know* tensors.

Warmup:
- A square is a rectangle, but a rectangle is not a square
- A square is a two-dimensional shape
- A cube is a three-dimensional shape
- A cube is a 3-D square
- A "hypercube" is a 4-D square

Alright, now that you're freaking' burning me with your hot brain, let's talk about tensors:
- A hypercube is a tensor, but a tensor is not a hypercube
- A tensor word for one or more rectangles smooshed together
- A rectangle is a tensor
- A cube is a tensor
- A hyper-cube (a 4-d cube) is a tensor
- "Tensor" means "some number of rectangles smooshed together"
- Replace rectangle with "matrix" in the above definition and you're a freaking genius!

I can tell you're smart because I know you know these things about squares and cubes:


Tensors are "n-dimensional" "rectagular" objects. By n-dimensional, I mean n-e-dimensional (haha get it). Let me show you using an example involving spreadsheets:
- n is 1: a list of numbers is a tensor (even if the list has only one number!).
- n is 2: a spreadsheet of numbers is a tensor.
- n is 3: a workbook with many sheets is a tensor.
- n is 4: a folder with workbooks is a tensor.
- n is 5: a folder of folders is a tensor.
- n it goes on n on!

Since it would be a drag to say something like "n-dimensional matrix" whenever we mean "some number of matrices smooshed together", we just say "tensor." I personally use the mental image of a workbook with many spreadsheets as my visual mental-model of what a tensor is.

To finish convincing you that you are already a tensor expert, let's talk about the two most important tensors in computer vision: the *black-and-white image* and the *color image.*

b&w image:
- length of "height" dimension: 200 pixels
- length of "width" dimension: 100 pixels
- length of color dimension: 1 channel (Grey)

mental model of a b&w image:
- a workbook with one sheet titled "Grey"
- the Grey sheet has 200 rows and 100 columns
- the Grey sheet has no column headers
- each cell in the sheet is a pixel
- each cell has a number in it from 0 (pure black) to 255 (pure white)

color image:
- length of "width" dimension: 100 pixels
- length of "height" dimension: 200 pixels
- length of color dimension: 3 channels (Red, Blue, Green)

mental model of a color image:
- a workbook of spreadsheets, just like the B&W image
- the workbook has three sheets instead of one: "Red", "Blue", and "Green"
- each cell in the Red sheet represent the red value for a single pixel
- each cell in the Blue sheet represent the blue value for a single pixel
- each cell in the Green sheet represent the green value for a single pixel