<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [ ]:
import torch

In [ ]:
pred_val = torch.rand(10)
pred_cls = torch.randint(3,7,(10,))
u_pred_cls, pred_cls_by_uidx = torch.unique(pred_cls, return_inverse=True)

pred_val, pred_cls, u_pred_cls, pred_cls_by_uidx

(tensor([0.0592, 0.2433, 0.1692, 0.3796, 0.9870, 0.3745, 0.0535, 0.6845, 0.5333,
         0.8284]),
 tensor([6, 4, 6, 5, 6, 4, 5, 6, 4, 6]),
 tensor([4, 5, 6]),
 tensor([2, 0, 2, 1, 2, 0, 1, 2, 0, 2]))

I want the result to be a list of lists:
- each list contains the indexes for the appearance of a specific class in preds

In [ ]:
[[p[0] for p,i in zip(nums,nums_by_uidx) if c==u] for u in u_pred_cls]

[[tensor(0), tensor(0), tensor(0)],
 [tensor(1), tensor(1), tensor(1)],
 [tensor(2), tensor(2)],
 [tensor(3), tensor(3)]]